import { SupportTicket } from "./SupportTicket.model";

export class Message {
    id?: number;  // ID of the message (optional, since it may be generated by the backend)
    roomId: number;  // ID of the room to which the message belongs
    sender?: string;  // Sender's name (optional)
    content: string;  // Content of the message
    timestamp?: string;
    ticket?:SupportTicket  // Timestamp of when the message was sent (optional)
  
    constructor(roomId: number, content: string, sender?: string, timestamp?: string, id?: number) {
      this.roomId = roomId;
      this.content = content;
      this.sender = sender;
      this.timestamp = timestamp;
      this.id = id;
    }
  }
  