apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  namespace: backend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/uploads
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: uploads-pv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/nexus?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  DB_USERNAME: root

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  DB_PASSWORD: c2Ficmk=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: nexus-backend
  template:
    metadata:
      labels:
        app: nexus-backend
    spec:
      containers:
        - name: backend
          image: tareksammoud/nexus-backend
          ports:
            - containerPort: 9000
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
            - name: app.storage.base-dir
              value: /data/uploads
          volumeMounts:
            - name: uploads-volume
              mountPath: /data/uploads
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-backend
  namespace: backend
  annotations:
    prometheus.io/scrape: "true"          # Enable Prometheus scraping
    prometheus.io/port: "9000"            # Port where your metrics are exposed
    prometheus.io/path: "/actuator/prometheus"  # The path for Prometheus metrics
spec:
  selector:
    app: nexus-backend
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000  # Optional: only needed if container uses a different port internally

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-backend-ingress
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    # Remove rewrite-target to preserve /nexus-backend
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - backend:
          service:
            name: nexus-backend
            port:
              number: 9000
        path: /nexus-backend
        pathType: Prefix
