apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/nexus?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
  DB_USERNAME: root

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
data:
  DB_PASSWORD: MTIzNDU2Nzg5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-backend
  namespace: backend
spec:
  selector:
    matchLabels:
      app: nexus-backend
  template:
    metadata:
      labels:
        app: nexus-backend
    spec:
      containers:
        - name: backend
          image: tareksammoud/nexus-backend
          ports:
            - containerPort: 9000
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-backend
  namespace: backend
spec:
  selector:
    app: nexus-backend
  ports:
    - port: 9000
