import { Component, OnInit } from '@angular/core';
import { JamService } from 'src/app/core/services/jam/jam.service';
import { Jam } from 'src/app/core/entities/Jam/jam';
import { Router } from '@angular/router';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Component({
  selector: 'app-admin-jams-list',
  templateUrl: './admin-jams-list.component.html',
  styleUrls: ['./admin-jams-list.component.css']
})
export class AdminJamsListComponent implements OnInit {
  jams: Jam[] = [];
  page = 1;

  constructor(private jamService: JamService, private router: Router) {}

  ngOnInit(): void {
    this.loadJams();
  }

  loadJams(): void {
    this.jamService.getJams().subscribe({
      next: (data) => this.jams = data,
      error: (err) => console.error('Error loading jams:', err)
    });
  }

  viewJam(jamId: number): void {
    this.router.navigate(['/admin/jams/details', jamId]);
  }

  editJam(jamId: number): void {
    this.router.navigate(['/admin/jams/edit', jamId]);
  }

  deleteJam(jamId: number): void {
    if (!confirm("Are you sure you want to delete this jam?")) return;
    this.jamService.deleteJam(jamId).subscribe(() => {
      this.jams = this.jams.filter(j => j.id !== jamId);
    });
  }

  getStatus(jam: Jam): 'upcoming' | 'active' | 'completed' {
    const now = Date.now();
    const devStart = new Date(jam.devStartDate).getTime();
    const voteEnd = new Date(jam.voteEndDate).getTime();
    if (now < devStart) return 'upcoming';
    if (now > voteEnd) return 'completed';
    return 'active';
  }

  exportPDF(): void {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const today = new Date().toLocaleString();
  
    const gradientSteps = 100;
    for (let i = 0; i < gradientSteps; i++) {
      const r = 0;
      const g = 124 + ((223 - 124) * i) / gradientSteps;
      const b = 240 + ((216 - 240) * i) / gradientSteps;
      doc.setFillColor(r, g, b);
      doc.rect((pageWidth / gradientSteps) * i, 0, pageWidth / gradientSteps + 1, 30, 'F');
    }
  
    const img: any = document.getElementById('pdfLogo');
    if (img && img instanceof HTMLImageElement) {
      doc.addImage(img, 'PNG', 10, 4, 18, 18);
    }
  
    doc.setFont('courier', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(255);
    doc.text('Game Jam Summary Report', pageWidth / 2, 18, { align: 'center' });
  
    const total = this.jams.length;
    const completed = this.jams.filter(j => this.getStatus(j) === 'completed').length;
    const active = this.jams.filter(j => this.getStatus(j) === 'active').length;
  
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`${total} Total | ${completed} Completed | ${active} Active`, pageWidth / 2, 25, { align: 'center' });
  
    doc.setTextColor(224); 
    doc.setFontSize(38);
    doc.setFont('courier', 'bold');
    doc.text('NEXUS SYSTEM', pageWidth / 2, pageHeight / 2, {
      angle: 45,
      align: 'center'
    });
  
    autoTable(doc, {
      startY: 38,
      head: [[ 'Name', 'Dev Dates', 'Vote Dates', 'Reward', 'Status']],
      body: this.jams.map(jam => [
        jam.name,
        `${this.formatShortDate(jam.devStartDate)} - ${this.formatShortDate(jam.devEndDate)}`,
        `${this.formatShortDate(jam.voteStartDate)} - ${this.formatShortDate(jam.voteEndDate)}`,
        jam.reward || 'None',
        this.getStatus(jam).toUpperCase()
      ]),
      theme: 'grid',
      headStyles: {
        fillColor: [30, 30, 30],
        textColor: 255,
        fontSize: 10,
        fontStyle: 'bold',
        halign: 'center'
      },
      bodyStyles: {
        font: 'helvetica',
        fontSize: 9,
        textColor: [50, 50, 50],
        cellPadding: 3
      },
      alternateRowStyles: {
        fillColor: [248, 248, 248]
      },
      styles: {
        halign: 'center',
        lineColor: [210, 210, 210],
        lineWidth: 0.1
      },
      margin: { left: 12, right: 12 }
    });
  
    doc.setDrawColor(180);
    doc.setLineWidth(0.3);
    doc.line(10, pageHeight - 25, pageWidth - 10, pageHeight - 25);
  
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text(`Printed on: ${today}`, 12, pageHeight - 20);
    doc.text('Generated by Nexus Game Jam Panel', 12, pageHeight - 13);
    doc.text('Signature automatique : Nexus Game Jam System', pageWidth - 12, pageHeight - 13, { align: 'right' });
  
    doc.save(`game-jams-${new Date().toISOString().slice(0, 10)}.pdf`);
  }
  
  
  formatShortDate(date: Date | string): string {
    return new Date(date).toLocaleDateString('fr-FR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric'
    });
  }
  
  
  private formatDate(date: string | Date): string {
    return new Date(date).toLocaleDateString();
  }
}
