package tn.arctic.nexus.controllers.FinanceModule.pdf;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.layout.properties.VerticalAlignment;
import lombok.extern.slf4j.Slf4j;
import tn.arctic.nexus.entities.FinanceModule.Payment;
import tn.arctic.nexus.entities.FinanceModule.Purchase;
import tn.arctic.nexus.entities.FinanceModule.Refund;
import tn.arctic.nexus.entities.FinanceModule.Transfer;

import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.TimeZone;

@Slf4j
public class PdfUtil {

    public static void writeTransactionsTableToPdf(List<?> transactions, String type, OutputStream out,
                                                   Date fromDate, Date toDate) throws Exception {
        PdfWriter writer = new PdfWriter(out);
        PdfDocument pdfDoc = new PdfDocument(writer);
        Document document = new Document(pdfDoc, PageSize.A4.rotate());

        // Custom colors
        DeviceRgb headerBlue = new DeviceRgb(25, 28, 35);
        DeviceRgb borderGray = new DeviceRgb(189, 195, 199);
        DeviceRgb userInfoGray = new DeviceRgb(108, 117, 125);

        PdfFont font = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        PdfFont fontBold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);

        // Create header table for logo and user info
        Table headerTable = new Table(UnitValue.createPercentArray(new float[]{1, 2}));
        headerTable.setWidth(UnitValue.createPercentValue(100));

        // Left cell for logo
        try {
            String logoPath = "src/main/resources/assets/logo.jpg";
            ImageData imageData = ImageDataFactory.create(logoPath);
            Image logo = new Image(imageData);
            logo.setWidth(50);

            Cell logoCell = new Cell()
                    .add(logo)
                    .setBorder(Border.NO_BORDER)
                    .setHorizontalAlignment(HorizontalAlignment.LEFT)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE);

            headerTable.addCell(logoCell);
        } catch (Exception e) {
            headerTable.addCell(new Cell().setBorder(Border.NO_BORDER));
            //System.out.println("Logo loading failed: " + e.getMessage());
        }

        // Right cell for user info
        SimpleDateFormat utcFormatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        utcFormatter.setTimeZone(TimeZone.getTimeZone("UTC"));
        String currentTimestamp = utcFormatter.format(new Date());

        Cell userInfoCell = new Cell()
                .add(new Paragraph()
                        .add(new Text("Current Date and Time (UTC): "))
                        .add(new Text(currentTimestamp).setBold())
                        .setFont(font)
                        .setFontSize(10))
                .add(new Paragraph()
                        .add(new Text("Generated By : "))
                        .add(new Text("Admin").setBold())
                        .setFont(font)
                        .setFontSize(10))
                .setBorder(Border.NO_BORDER)
                .setTextAlignment(TextAlignment.RIGHT)
                .setVerticalAlignment(VerticalAlignment.MIDDLE);

        headerTable.addCell(userInfoCell);
        document.add(headerTable);

        // Add spacing after header
        document.add(new Paragraph().setMarginBottom(20));

        // Platform name
        Paragraph platformName = new Paragraph("Nexus")
                .setFont(fontBold)
                .setFontSize(24)
                .setFontColor(headerBlue)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(10);
        document.add(platformName);

        // Date range with better formatting
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String dateRange = String.format("Report Period: %s to %s",
                sdf.format(fromDate),
                sdf.format(toDate));

        Paragraph dateRangePara = new Paragraph(dateRange)
                .setFont(font)
                .setFontSize(12)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(20)
                .setFontColor(userInfoGray);
        document.add(dateRangePara);

        // Report title
        Paragraph title = new Paragraph("Transaction Report: " + capitalize(type))
                .setFont(fontBold)
                .setFontSize(20)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginBottom(30)
                .setFontColor(headerBlue);
        document.add(title);

        // Create and add table based on transaction type
        Table table = null;
        switch (type.toLowerCase()) {
            case "payment":
                table = createPaymentTable((List<Payment>) transactions, font, fontBold, borderGray, borderGray);
                break;
            case "purchase":
                table = createPurchaseTable((List<Purchase>) transactions, font, fontBold, borderGray, borderGray);
                break;
            case "refund":
                table = createRefundTable((List<Refund>) transactions, font, fontBold, borderGray, borderGray);
                break;
            case "transfer":
                table = createTransferTable((List<Transfer>) transactions, font, fontBold, borderGray, borderGray);
                break;
        }

        if (table != null) {
            table.setHorizontalAlignment(HorizontalAlignment.CENTER);
            table.setWidth(UnitValue.createPercentValue(100));
            document.add(table);
        } else {
            document.add(new Paragraph("No data available for the selected period.")
                    .setFont(font)
                    .setFontSize(12)
                    .setTextAlignment(TextAlignment.CENTER));
        }

        // Add footer with page number
        int pageNum = pdfDoc.getNumberOfPages();
        Paragraph footer = new Paragraph(String.format("Page %d", pageNum))
                .setFont(font)
                .setFontSize(10)
                .setTextAlignment(TextAlignment.CENTER)
                .setMarginTop(20)
                .setFontColor(borderGray);
        document.add(footer);

        document.close();
        pdfDoc.close();
        writer.close();
    }


    private static Table createPaymentTable(List<Payment> payments, PdfFont font, PdfFont fontBold,
                                            DeviceRgb headerColor, DeviceRgb borderColor) {
        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 6, 5, 5, 8}));
        table.setBorder(new SolidBorder(borderColor, 1));

        // Add headers
        String[] headers = {"ID", "Coin Amount", "Status", "Price", "Created At"};
        for (String header : headers) {
            table.addHeaderCell(
                    new Cell()
                            .add(new Paragraph(header)
                                    .setFont(fontBold)
                                    .setFontSize(13)
                                    .setFontColor(ColorConstants.WHITE))
                            .setBackgroundColor(headerColor)
                            .setTextAlignment(TextAlignment.CENTER)
                            .setVerticalAlignment(VerticalAlignment.MIDDLE)
                            .setPadding(12)
            );
        }

        // Add data rows with alternating colors
        DeviceRgb altColor = new DeviceRgb(249, 249, 249);
        int rowCount = 0;

        for (Payment p : payments) {
            rowCount++;
            DeviceRgb backgroundColor = (rowCount % 2 == 0) ? altColor : (DeviceRgb) ColorConstants.WHITE;

            addCenteredCell(table, String.valueOf(p.getId()), font, backgroundColor);
            addCenteredCell(table, String.valueOf(p.getCoinAmount()), font, backgroundColor);

            // Status cell with color coding
            Cell statusCell = new Cell()
                    .add(new Paragraph(p.getStatus()).setFont(font))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setPadding(8)
                    .setBackgroundColor(backgroundColor);

            // Color code the status
            if ("Completed".equalsIgnoreCase(p.getStatus())) {
                statusCell.setFontColor(new DeviceRgb(46, 204, 113));
            } else if ("Pending".equalsIgnoreCase(p.getStatus())) {
                statusCell.setFontColor(new DeviceRgb(243, 156, 18));
            }
            table.addCell(statusCell);

            addCenteredCell(table, p.getPrice(), font, backgroundColor);
            addCenteredCell(table, formatDate(p.getCreatedAt()), font, backgroundColor);
        }

        return table;
    }
    private static Table createPurchaseTable(List<Purchase> purchases, PdfFont font, PdfFont fontBold,
                                             DeviceRgb headerColor, DeviceRgb borderColor) {
        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 6, 5, 5, 8, 4}));
        table.setBorder(new SolidBorder(borderColor, 1));

        // Add headers
        String[] headers = {"ID", "Product Type", "Product ID", "Price", "Created At", "Wallet ID"};
        for (String header : headers) {
            table.addHeaderCell(
                    new Cell()
                            .add(new Paragraph(header)
                                    .setFont(fontBold)
                                    .setFontSize(13)
                                    .setFontColor(ColorConstants.WHITE))
                            .setBackgroundColor(headerColor)
                            .setTextAlignment(TextAlignment.CENTER)
                            .setVerticalAlignment(VerticalAlignment.MIDDLE)
                            .setPadding(12)
            );
        }

        // Add data rows with alternating colors
        DeviceRgb altColor = new DeviceRgb(249, 249, 249);
        int rowCount = 0;

        for (Purchase p : purchases) {
            rowCount++;
            DeviceRgb backgroundColor = (rowCount % 2 == 0) ? altColor : (DeviceRgb) ColorConstants.WHITE;

            addCenteredCell(table, String.valueOf(p.getId()), font, backgroundColor);
            addCenteredCell(table, p.getProductType() != null ? p.getProductType().toString() : "", font, backgroundColor);
            addCenteredCell(table, p.getProductId() != null ? p.getProductId().toString() : "", font, backgroundColor);
            addCenteredCell(table, p.getPrice() != null ? p.getPrice().toString() : "", font, backgroundColor);
            addCenteredCell(table, formatDate(p.getCreatedAt()), font, backgroundColor);
            addCenteredCell(table, p.getWallet() != null && p.getWallet().getId() != null ?
                    p.getWallet().getId().toString() : "", font, backgroundColor);
        }

        return table;
    }

    private static Table createRefundTable(List<Refund> refunds, PdfFont font, PdfFont fontBold,
                                           DeviceRgb headerColor, DeviceRgb borderColor) {
        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 6, 5, 7, 8, 4}));
        table.setBorder(new SolidBorder(borderColor, 1));

        // Add headers
        String[] headers = {"ID", "Status", "Refund Amount", "Reason", "Created At", "Purchase ID"};
        for (String header : headers) {
            table.addHeaderCell(
                    new Cell()
                            .add(new Paragraph(header)
                                    .setFont(fontBold)
                                    .setFontSize(13)
                                    .setFontColor(ColorConstants.WHITE))
                            .setBackgroundColor(headerColor)
                            .setTextAlignment(TextAlignment.CENTER)
                            .setVerticalAlignment(VerticalAlignment.MIDDLE)
                            .setPadding(12)
            );
        }

        // Add data rows with alternating colors
        DeviceRgb altColor = new DeviceRgb(249, 249, 249);
        int rowCount = 0;

        for (Refund r : refunds) {
            rowCount++;
            DeviceRgb backgroundColor = (rowCount % 2 == 0) ? altColor : (DeviceRgb) ColorConstants.WHITE;

            addCenteredCell(table, String.valueOf(r.getId()), font, backgroundColor);

            // Status cell with color coding
            Cell statusCell = new Cell()
                    .add(new Paragraph(r.getStatus()).setFont(font))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setPadding(8)
                    .setBackgroundColor(backgroundColor);

            // Color code the status
            if ("Approved".equalsIgnoreCase(r.getStatus())) {
                statusCell.setFontColor(new DeviceRgb(46, 204, 113)); // Green
            } else if ("Pending".equalsIgnoreCase(r.getStatus())) {
                statusCell.setFontColor(new DeviceRgb(243, 156, 18)); // Orange
            } else if ("Rejected".equalsIgnoreCase(r.getStatus())) {
                statusCell.setFontColor(new DeviceRgb(231, 76, 60)); // Red
            }
            table.addCell(statusCell);

            addCenteredCell(table, r.getRefundAmount() != null ? r.getRefundAmount().toString() : "", font, backgroundColor);
            addCenteredCell(table, r.getReason(), font, backgroundColor);
            addCenteredCell(table, formatDate(r.getCreatedAt()), font, backgroundColor);
            addCenteredCell(table, r.getPurchase() != null && r.getPurchase().getId() != null ?
                    r.getPurchase().getId().toString() : "", font, backgroundColor);
        }

        return table;
    }

    private static Table createTransferTable(List<Transfer> transfers, PdfFont font, PdfFont fontBold,
                                             DeviceRgb headerColor, DeviceRgb borderColor) {
        Table table = new Table(UnitValue.createPercentArray(new float[]{3, 8, 8, 5, 5, 8, 4}));
        table.setBorder(new SolidBorder(borderColor, 1));

        // Add headers
        String[] headers = {"ID", "Receiver", "Sender", "Amount", "Type", "Created At", "Wallet ID"};
        for (String header : headers) {
            table.addHeaderCell(
                    new Cell()
                            .add(new Paragraph(header)
                                    .setFont(fontBold)
                                    .setFontSize(13)
                                    .setFontColor(ColorConstants.WHITE))
                            .setBackgroundColor(headerColor)
                            .setTextAlignment(TextAlignment.CENTER)
                            .setVerticalAlignment(VerticalAlignment.MIDDLE)
                            .setPadding(12)
            );
        }

        // Add data rows with alternating colors
        DeviceRgb altColor = new DeviceRgb(249, 249, 249);
        int rowCount = 0;

        for (Transfer t : transfers) {
            rowCount++;
            DeviceRgb backgroundColor = (rowCount % 2 == 0) ? altColor : (DeviceRgb) ColorConstants.WHITE;

            addCenteredCell(table, String.valueOf(t.getId()), font, backgroundColor);
            addCenteredCell(table, t.getReceiverMetaMaskAddress(), font, backgroundColor);
            addCenteredCell(table, t.getSenderMetaMaskAddress(), font, backgroundColor);
            addCenteredCell(table, t.getAmount() != null ? t.getAmount().toString() : "", font, backgroundColor);

            // Transfer type with color coding
            Cell typeCell = new Cell()
                    .add(new Paragraph(t.getType() != null ? t.getType().toString() : "").setFont(font))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setPadding(8)
                    .setBackgroundColor(backgroundColor);

            // Color code the transfer type if needed
            if (t.getType() != null) {
                switch (t.getType().toString().toUpperCase()) {
                    case "INTERNAL":
                        typeCell.setFontColor(new DeviceRgb(52, 152, 219)); // Blue
                        break;
                    case "EXTERNAL":
                        typeCell.setFontColor(new DeviceRgb(155, 89, 182)); // Purple
                        break;
                    default:
                        typeCell.setFontColor(ColorConstants.BLACK);
                }
            }
            table.addCell(typeCell);

            addCenteredCell(table, formatDate(t.getCreatedAt()), font, backgroundColor);
            addCenteredCell(table, t.getWallet() != null && t.getWallet().getId() != null ?
                    t.getWallet().getId().toString() : "", font, backgroundColor);
        }

        return table;
    }
    private static void addCenteredCell(Table table, String content, PdfFont font, DeviceRgb backgroundColor) {
        table.addCell(
                new Cell()
                        .add(new Paragraph(content).setFont(font))
                        .setTextAlignment(TextAlignment.CENTER)
                        .setVerticalAlignment(VerticalAlignment.MIDDLE)
                        .setPadding(8)
                        .setBackgroundColor(backgroundColor)
        );
    }

    private static String formatDate(Date date) {
        if (date == null) return "";
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        return sdf.format(date);
    }

    private static String capitalize(String str) {
        if (str == null || str.isEmpty()) return str;
        return str.substring(0, 1).toUpperCase() + str.substring(1).toLowerCase();
    }

}
