package tn.arctic.nexus.repositories.TechnicalSupportModule;

import org.springframework.data.jpa.repository.JpaRepository;
import tn.arctic.nexus.entities.PerformanceReview;

import java.util.List;
import java.util.Optional;

public interface IPerformanceReviewRepository extends JpaRepository<PerformanceReview, Long> {


    // Corrected: Removed static keyword and defined as an instance method
    List<PerformanceReview> findBySupportAgentId(Long agentId); // Automatically generated by Spring Data JPA

    boolean existsBySupportAgentId(Long id); // Automatically generated by Spring Data JPA
}
