worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Global body size limit
    client_max_body_size 500M;  # Set your desired limit here

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logging
    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log;

    include /etc/nginx/conf.d/*.conf;  # Include all the configs from conf.d directory
}
