server {
    listen 4200;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # This ensures Angular routes correctly
    }
    location /api/ {
    proxy_pass /api;
    }
    location /recommendation-ai/ {
    proxy_pass http://nexus-backend.backend.svc.cluster.local:9000/;
    }
    location /spam-ai/ {
    proxy_pass http://spam-ai.ai.svc.cluster.local:5001;
    }
    location /style-ai/ {
    proxy_pass http://style-ai.ai.svc.cluster.local:5003;
    }
    location /support-ai/ {
    proxy_pass http://support-ai.ai.svc.cluster.local:5002;
    }
    location /toxic-ai/ {
    proxy_pass http://toxic-ai.ai.svc.cluster.local:5004;
    }
}

