package tn.arctic.nexus.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Primary key for the Message entity

    @ManyToOne
    @JoinColumn(name = "room_id", nullable = false) // Foreign key to Room entity
    private Room room;
 // Ensures that the sender cannot be null

    private String sender;

 // Ensures that the content cannot be null
    private String content;

    @Column(nullable = false) // Ensures that timestamp is never null
    private LocalDateTime timestamp;

    @ManyToOne
    @JoinColumn(name = "ticket_id") // or appropriate column name
    private SupportTicket ticket;

    // Constructor, getters and setters are auto-generated by Lombok annotations
}
