spring.application.name=nexus-backend
spring.datasource.url=jdbc:mysql://localhost:3306/nexus?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=3005
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/nexus-backend
server.port=9000



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medalilahmar00@gmail.com
spring.mail.password=zzdn bpyh pnmx awby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
